# config/meta.yml

meta_product_name: "ChefMe"
meta_title: "ChefMe - Let your inner chef out!"
meta_description: "Find recipes based on whatever you have in your fridge."
meta_image: "becca-tapert-O7sK3d3TPWQ-unsplash.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
